version: '3.8'
services:
  smartmeter1:
    container_name: smartmeter1_reader
    build:
      context: .
    privileged: true # needed for accessing usb
    restart: unless-stopped
    environment:
      - COMPORT=/dev/ttyUSB0
      - KEY=$ReaderKey
      - LOG_LEVEL=1 # 0 - nothing; 1 - only debug; 2 - debug and data
      - MQTT_BROKER=$MQTT_HOST
      - MQTT_PORT=1883
      - MQTT_USER=$MQTT_USER
      - MQTT_PASSWORD=$MQTT_PASSWORD
      - DEVICE_NAME=Smartmeter
    networks:
      - smartmeterNetwork

  smartmeter2:
    container_name: smartmeter2_reader
    build:
      context: .
    privileged: true # needed for accessing usb
    restart: unless-stopped
    environment:
      - COMPORT=/dev/ttyUSB1
      - KEY=$ReaderKey2
      - LOG_LEVEL=1 # 0 - nothing; 1 - only debug; 2 - debug and data
      - MQTT_BROKER=$MQTT_HOST
      - MQTT_PORT=1883
      - MQTT_USER=$MQTT_USER
      - MQTT_PASSWORD=$MQTT_PASSWORD
      - DEVICE_NAME=Smartmeter2
    networks:
      - smartmeterNetwork

networks:
  smartmeterNetwork:
    driver: bridge
