name: SmartmeterHA
version: '1.0.0'
slug: smartmeter
description: Auslesen von Kaifa MA309 Stromzählern und bereitstellung der Daten über MQTT.
url: https://github.com/Simeon-byte/SmartMeterHA
arch:
    - amd64
    - aarch64
    - armv7
startup: application
boot: auto
init: false
uart: true
services:
    - mqtt:need
options:
    key: null
    comport: /dev/ttyUSB0
    device_name: SmartMeterVKW
    log_level: info
schema:
    key: password
    comport: device(subsystem=tty)
    device_name: str
    log_level: list(error|warning|info|debug|trace)
stage: experimental
